---
title: "rds_files_to_single_dataframe"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This R script reads multiple .rds files from a specified directory, combines them into a single data frame, and saves the combined data as an .rds file. The script automates the process of combining data from multiple files into one.

```{r}
# Load necessary library
library(dplyr)

# Define input directory and output file path
input_dir <- "D:/IntroDataScienceProject/crema-d-mirror/AllDataFrames"
output_file <- "all_pitch(63).rds"  # Replace with your desired output file path
setwd("D:/IntroDataScienceProject/crema-d-mirror")
# List all .rds files in the input directory
rds_files <- list.files(path = input_dir, pattern = "\\.rds$", full.names = TRUE)

# Function to read each .rds file
read_rds_and_rbind <- function(file) {
  data <- readRDS(file)
  return(data)
}

# Use lapply to read each .rds file and combine them into a single data frame
combined_data <- lapply(rds_files, read_rds_and_rbind) %>%
  bind_rows()

# Save the combined data frame as a single .rds file
saveRDS(combined_data, file = output_file)

# Update 'input_dir' with the folder containing the .rds files and 'output_file' with the desired output path.

```


